### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by batjko** [oanda/spread_for_node#2]
Hi,

After using npm to install this and failing, I tried cloning this repo and locally installing the dependencies, but one of it seems to want to build binaries using `make`, which of course won't work on Windows.

Can I just confirm if there is a way of making this work on a Windows-based machine?

Thanks.

**Comment by abendigo** [comment]
Batjko,

  Sorry for the delay in getting back to you. I never tried running this in Windows, so I am unsure if it will work. I am setting up a windows VM now to test, and I'll let you know what I find.

**Comment by abendigo** [comment]
So I looked into this a little. Unfortunately, this project requires log4js, which somewhere deep down depends on compress-buffer, and that requires make to build. Short of refactoring this code to no longer rely on log4js, it is not possible to make it run on windows.

**Comment by batjko** [comment]
Hi @abendigo.

Ok, understood. Thanks for looking into it!
I suppose this could be a nice little challenge for someone who knows their way around log4j or replacing it.

**Comment by abendigo** [comment]
I just updated bower.json to point to a newer version of log4js. It seems to work for me on windows, but I don't have a spread server to connect to anymore to really test it.
